title: CS 186
baseurl: /cs186
email: tammynguyen@berkeley.edu

highlighter: rouge
markdown: kramdown

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

exclude:
- README.md


plugins: [jekyll-seo-tag, jekyll-paginate]
